<a href="https://colab.research.google.com/github/HarinCoder/HarinCoder/blob/main/Harin_DIY_Day15_answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. **Problem Statement: Data Grouping -ILoad the “big_bang_theory.csv”dataset  provided  on  LMS  into  a  DataFrame, group the data based on column "directed_by"using the groupby()function and  the  grouped  DataFrame.  Now  alsoprint  all  the  episodes  and  the  data associated with them, which belongs to the director -Mark Cendroski**

In [2]:
import pandas as pd

df = pd.read_csv("big_bang_theory_episodes.csv")
display(df)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,James Burrows,Chuck Lorre & Bill Prady,2007-09-24,276023,9520000.0
1,1,2,2,The Big Bran Hypothesis,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Mark Cendrowski,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
4,1,5,5,The Hamburger Postulate,Andrew D. Weyman,Story by: Jennifer GlickmanTeleplay by: Dave G...,2007-10-22,3T6604,8810000.0
...,...,...,...,...,...,...,...,...,...
274,12,20,275,The Decision Reverberation,Mark Cendrowski,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
275,12,21,276,The Plagiarism Schism,Nikki Lorre,Story by: Eric Kaplan & Maria Ferrari & Adam F...,2019-05-02,T12.16021,12480000.0
276,12,22,277,The Maternal Conclusion,Kristy Cecil,Story by: Steve Holland & Eric Kaplan & Jeremy...,2019-05-09,T12.16022,12590000.0
277,12,23,278,The Change Constant,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

Printing the first group from grouped DataFrame:

In [15]:
first_group = (df.groupby('directed_by').count())
                         
display(first_group)

,season,episode_num_in_season,episode_num_overall,title,written_by,original_air_date,prod_code,us_viewers
directed_by,,,,,,,,
Andrew D. Weyman,1,1,1,1,1,1,1,1
Anthony Rich,12,12,12,12,12,12,12,12
Gay Linvill,2,2,2,2,2,2,2,2
Howard Murray,2,2,2,2,2,2,2,2
James Burrows,1,1,1,1,1,1,1,1
Joel Murray,1,1,1,1,1,1,1,1
Kristy Cecil,2,2,2,2,2,2,2,2
Mark Cendrowski,244,244,244,244,244,244,244,244
Nikki Lorre,6,6,6,6,6,6,6,6
Peter Chakos,7,7,7,7,7,7,7,7
Ted Wass,1,1,1,1,1,1,1,1

Displaying the group related to director-Mark Cendrowski:

In [14]:
i = (df.groupby("directed_by").get_group("Mark Cendrowski"))

display(i)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
1,1,2,2,The Big Bran Hypothesis,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Mark Cendrowski,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
5,1,6,6,The Middle Earth Paradigm,Mark Cendrowski,Story by: Dave GoetschTeleplay by: David Litt ...,2007-10-29,3T6605,8920000.0
6,1,7,7,The Dumpling Paradox,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-11-05,3T6606,9680000.0
...,...,...,...,...,...,...,...,...,...
272,12,18,273,The Laureate Accumulation,Mark Cendrowski,Story by: Steve Holland & Adam Faberman & Davi...,2019-04-04,T12.16018,12220000.0
273,12,19,274,The Inspiration Deprivation,Mark Cendrowski,Story by: Eric Kaplan & Maria Ferrari & Andy G...,2019-04-18,T12.16019,11440000.0
274,12,20,275,The Decision Reverberation,Mark Cendrowski,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
277,12,23,278,The Change Constant,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

**2. Problem Statement: Data Grouping -IILoad the “big_bang_theory.csv”dataset  provided  on  LMS  into  a  DataFrame; Group  the data based  on  two columns, "directed_by"and "written_by,"using the groupby()function and print  the  grouped DataFrame.Also,  print  the average viewers in the United Statesand thedirector andthewriter'sdetails**

In [16]:
import pandas as pd 

df = pd.read_csv("big_bang_theory_episodes.csv")
display(df)

,season,episode_num_in_season,episode_num_overall,title,directed_by,written_by,original_air_date,prod_code,us_viewers
0,1,1,1,Pilot,James Burrows,Chuck Lorre & Bill Prady,2007-09-24,276023,9520000.0
1,1,2,2,The Big Bran Hypothesis,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-01,3T6601,8580000.0
2,1,3,3,The Fuzzy Boots Corollary,Mark Cendrowski,Story by: Chuck LorreTeleplay by: Bill Prady &...,2007-10-08,3T6602,8360000.0
3,1,4,4,The Luminous Fish Effect,Mark Cendrowski,Story by: Chuck Lorre & Bill PradyTeleplay by:...,2007-10-15,3T6603,8150000.0
4,1,5,5,The Hamburger Postulate,Andrew D. Weyman,Story by: Jennifer GlickmanTeleplay by: Dave G...,2007-10-22,3T6604,8810000.0
...,...,...,...,...,...,...,...,...,...
274,12,20,275,The Decision Reverberation,Mark Cendrowski,Story by: Steven Molaro & Steve Holland & Tara...,2019-04-25,T12.16020,11840000.0
275,12,21,276,The Plagiarism Schism,Nikki Lorre,Story by: Eric Kaplan & Maria Ferrari & Adam F...,2019-05-02,T12.16021,12480000.0
276,12,22,277,The Maternal Conclusion,Kristy Cecil,Story by: Steve Holland & Eric Kaplan & Jeremy...,2019-05-09,T12.16022,12590000.0
277,12,23,278,The Change Constant,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16023,18520000.0
278,12,24,279,The Stockholm Syndrome,Mark Cendrowski,Chuck Lorre & Steve Holland & Steven Molaro & ...,2019-05-16,T12.16024,18520000.0

In [25]:
lm = (df.groupby(["directed_by", "written_by"]).mean())


display(lm)
display("its size is : ",lm.size)
display("its length is : ",len(lm))

                                                                     season  \
directed_by      written_by
Andrew D. Weyman Story by: Jennifer GlickmanTeleplay by: Dave Go...     1.0
Anthony Rich     Chuck Lorre & Bill Prady & Lee Aronsohn & Steve...     3.0
                 Story by: Bill Prady & Eric Kaplan & Jim Reynol...     7.0
                 Story by: Chuck Lorre & Bill Prady & Dave Goets...     4.0
                 Story by: Chuck Lorre & Bill Prady & Steve Holl...     5.0
...                                                                     ...
Peter Chakos     Story by: Chuck Lorre & Eric Kaplan & Adam Fabe...     6.0
                 Story by: Chuck Lorre & Jim Reynolds & Jeremy H...     7.0
                 Story by: Chuck Lorre & Lee Aronsohn & Steven M...     3.0
                 Story by: Chuck Lorre & Steven Molaro & Maria F...     4.0
Ted Wass         Story by: Dave Goetsch & Steven MolaroTeleplay ...     1.0

                                                                     episode_num_in_season  \
directed_by      written_by
Andrew D. Weyman Story by: Jennifer GlickmanTeleplay by: Dave Go...                    5.0
Anthony Rich     Chuck Lorre & Bill Prady & Lee Aronsohn & Steve...                   20.0
                 Story by: Bill Prady & Eric Kaplan & Jim Reynol...                   19.0
                 Story by: Chuck Lorre & Bill Prady & Dave Goets...                   13.0
                 Story by: Chuck Lorre & Bill Prady & Steve Holl...                   11.0
...                                                                                    ...
Peter Chakos     Story by: Chuck Lorre & Eric Kaplan & Adam Fabe...                    9.0
                 Story by: Chuck Lorre & Jim Reynolds & Jeremy H...                   23.0
                 Story by: Chuck Lorre & Lee Aronsohn & Steven M...                   16.0
                 Story by: Chuck Lorre & Steven Molaro & Maria F...                   19.0
Ted Wass         Story by: Dave Goetsch & Steven MolaroTeleplay ...                    8.0

                                                                     episode_num_overall  \
directed_by      written_by
Andrew D. Weyman Story by: Jennifer GlickmanTeleplay by: Dave Go...                  5.0
Anthony Rich     Chuck Lorre & Bill Prady & Lee Aronsohn & Steve...                 60.0
                 Story by: Bill Prady & Eric Kaplan & Jim Reynol...                154.0
                 Story by: Chuck Lorre & Bill Prady & Dave Goets...                 76.0
                 Story by: Chuck Lorre & Bill Prady & Steve Holl...                 98.0
...                                                                                  ...
Peter Chakos     Story by: Chuck Lorre & Eric Kaplan & Adam Fabe...                120.0
                 Story by: Chuck Lorre & Jim Reynolds & Jeremy H...                158.0
                 Story by: Chuck Lorre & Lee Aronsohn & Steven M...                 56.0
                 Story by: Chuck Lorre & Steven Molaro & Maria F...                 82.0
Ted Wass         Story by: Dave Goetsch & Steven MolaroTeleplay ...                  8.0

                                                                     us_viewers
directed_by      written_by
Andrew D. Weyman Story by: Jennifer GlickmanTeleplay by: Dave Go...   8810000.0
Anthony Rich     Chuck Lorre & Bill Prady & Lee Aronsohn & Steve...  11630000.0
                 Story by: Bill Prady & Eric Kaplan & Jim Reynol...  17730000.0
                 Story by: Chuck Lorre & Bill Prady & Dave Goets...  13630000.0
                 Story by: Chuck Lorre & Bill Prady & Steve Holl...  14020000.0
...                                                                         ...
Peter Chakos     Story by: Chuck Lorre & Eric Kaplan & Adam Fabe...  17250000.0
                 Story by: Chuck Lorre & Jim Reynolds & Jeremy H...  14420000.0
                 Story by: Chuck Lorre & Lee Aronsohn & Steven M...  15730000.0
                 Story by: Chuck Lorre & Steven Molaro & Maria F...  11920000.0
Ted Wass         Story by: Dave Goetsch & Steven MolaroTeleplay ...   9320000.0

[261 rows x 4 columns]

'its size is : '

1044

'its length is : '

261